version: '3.7'
services:

  #PHP-fpm - service

  app:
    build:
      context: ../project/
      dockerfile: ../deploy/Dockerfile
    container_name: app_container
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ../project/:/var/www
      - ./docker-files/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #NGNX - service

  webserver:
    image: nginx:alpine
    container_name: webserver_container
    restart: unless-stopped
    tty: true

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../project/:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/

    networks:
      - app-network

  #MariaDB - service


  db:
    image: postgres:13.2-alpine
    container_name: db_container
    tty: true
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "lumen"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - postgresdbdata:/var/lib/postgresql/data

    networks:
      - app-network

  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4

      environment:
        PGADMIN_DEFAULT_EMAIL: email@mail.com
        PGADMIN_DEFAULT_PASSWORD: 123456

      ports:
        - "5050:80"

volumes:
  postgresdbdata:
    driver: local

#NETWORKS

networks:
  app-network:
    driver: bridge
