version: '3.7'
services:

  app:
    build:
      context: ../project/
      dockerfile: ../deploy/docker-files/php/Dockerfile
    container_name: app_container
    restart: unless-stopped
    tty: true
    working_dir: /var/www

    volumes:
      - ../project/:/var/www
      - ./docker-files/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network

  webserver:
    container_name: webserver_container
    build: docker-files/nginx
    restart: unless-stopped
    tty: true

    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../project/:/var/www
      - ./docker-files/nginx/conf.d/:/etc/nginx/conf.d/
      - ../project/public:/var/www/public

    networks:
      - app-network

  db:
    image: postgres:13.2-alpine
    container_name: db
    tty: true
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: "lumen"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgresdbdata:/var/lib/postgresql/data

    networks:
      - app-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4

    environment:
      PGADMIN_DEFAULT_EMAIL: email@mail.com
      PGADMIN_DEFAULT_PASSWORD: 123456

    ports:
      - "5050:80"

  composer:
    container_name: composer_container
    image: composer
    command: composer install --ignore-platform-reqs
    volumes:
      - ../project/:/app
    networks:
      - app-network


volumes:
  postgresdbdata:
    driver: local

networks:
  app-network:
    driver: bridge
